project_name: bpm-cli
before:
  hooks:
    - go mod download # Download once at the start because goreleaser builds in parallel (https://goreleaser.com/customization/)
builds:
- main: ./cmd/main.go
  ldflags:
    - -X main.version={{.Version}}
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  binary: bpm
# archives: // Commented out because the defaults are just fine
# checksum: // Commented out because the defaults are just fine
nfpms:
  - formats:
    - deb
    - rpm
    vendor: Blockdaemon
    homepage: https://blockdaemon.com
    maintainer: Blockdaemon <support@blockdaemon.com>
    description: Blockchain Package Manager. Deploy, maintain, and upgrade blockchain nodes on your own infrastructure.
    license: Apache 2.0
    recommends:
      - docker-ce
brews:
  - gitlab:
      owner: blockdaemon
      name: homebrew-tap
    homepage: https://blockdaemon.com
    description: Blockchain Package Manager. Deploy, maintain, and upgrade blockchain nodes on your own infrastructure.
signs:
  - artifacts: all
    args: ["-u", "F08C9DBB7215EC0FBC887A9E30F518E8C905E87B", "--output", "${signature}", "--detach-sign", "${artifact}"]
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  gitlab:
    owner: blockdaemon
    name: bpm-cli

