swagger: '2.0'
info:
  title: Blockchain Package Manager
  contact:
    email: support@blockdaemon.com
    url: https://www.blockdaemon.com
  x-logo:
    url: "https://images.ctfassets.net/rasr8fpc604w/4SkzlDeysPc2lGkv7JttCm/1b128e1d30f42336015e30ddec3c138f/dark-logo.png"
    backgroundColor: "#fafafa"
    altText: Blockdaemon logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: 
    $ref: docs/documentation.md